// Generated by LeanRustCore from elaborated Lean declarations. Do not edit by hand.
// The checked-in rust/src/generated.rs is a fallback snapshot; scripts/gen.sh regenerates it.

#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum Choice { First, Second }

pub fn clamp_u32(lo: u32, hi: u32, x: u32) -> u32 {
    if x < lo { lo } else { if hi < x { hi } else { x } }
}

pub fn max_u32(a: u32, b: u32) -> u32 {
    if a < b { b } else { a }
}

pub fn is_nonzero_u32(x: u32) -> bool {
    if x == 0 { false } else { true }
}

pub fn add_u32(a: u32, b: u32) -> u32 {
    (a).wrapping_add(b)
}

pub fn mul_u32(a: u32, b: u32) -> u32 {
    (a).wrapping_mul(b)
}

pub fn bounded_bump_u32(x: u32) -> u32 {
    { let y = (x).wrapping_add(1); if 10 < y { 10 } else { y } }
}

pub fn echo_u32(x: u32) -> u32 {
    x
}

pub fn echo_u64(x: u64) -> u64 {
    x
}

pub fn echo_i32(x: i32) -> i32 {
    x
}

pub fn echo_i64(x: i64) -> i64 {
    x
}

pub fn add_u64(a: u64, b: u64) -> u64 {
    (a).wrapping_add(b)
}

pub fn unit_roundtrip(x: ()) -> () {
    x
}

pub fn bool_match_u32(flag: bool, when_true: u32, when_false: u32) -> u32 {
    match flag { true => when_true, false => when_false }
}

pub fn option_identity_u32(x: Option<u32>) -> Option<u32> {
    x
}

pub fn none_u32(_x: ()) -> Option<u32> {
    None
}

pub fn some_u32(x: u32) -> Option<u32> {
    Some(x)
}

pub fn option_default_u32(x: Option<u32>, fallback: u32) -> u32 {
    match x { None => fallback, Some(value) => value }
}

pub fn result_ok_u32(x: u32) -> Result<u32, u32> {
    Ok(x)
}

pub fn result_err_u32(e: u32) -> Result<u32, u32> {
    Err(e)
}

pub fn choose_by_enum(choice: Choice, left: u32, right: u32) -> u32 {
    match choice { Choice::First => left, Choice::Second => right }
}
