// Generated by LeanRustCore from elaborated Lean declarations. Do not edit by hand.
// The checked-in rust/src/generated.rs is a fallback snapshot; scripts/gen.sh regenerates it.

pub fn clamp_u32(lo: u32, hi: u32, x: u32) -> u32 {
    if (x < lo) { lo } else { if (hi < x) { hi } else { x } }
}

pub fn max_u32(a: u32, b: u32) -> u32 {
    if (a < b) { b } else { a }
}

pub fn is_nonzero_u32(x: u32) -> bool {
    if (x == 0) { false } else { true }
}

pub fn add_u32(a: u32, b: u32) -> u32 {
    (a).wrapping_add(b)
}

pub fn mul_u32(a: u32, b: u32) -> u32 {
    (a).wrapping_mul(b)
}

pub fn bounded_bump_u32(x: u32) -> u32 {
    { let y = (x).wrapping_add(1); if (10 < y) { 10 } else { y } }
}
