// Generated by LeanRustCore.Differential. Do not edit by hand.
// Expectations on the right-hand side are computed in Lean.

use lean_rust_core_generated::*;
use num_bigint::{BigInt, BigUint};

#[test]
fn lean_ir_evaluator_matches_generated_rust() {
    assert_eq!(clamp_u32(10, 20, 5), 10u32);
    assert_eq!(clamp_u32(10, 20, 25), 20u32);
    assert_eq!(clamp_u32(10, 20, 15), 15u32);
    assert_eq!(max_u32(3, 8), 8u32);
    assert_eq!(max_u32(8, 3), 8u32);
    assert!(!is_nonzero_u32(0));
    assert!(is_nonzero_u32(7));
    assert_eq!(add_u32(u32::MAX, 1), 0u32);
    assert_eq!(add_u32(40, 2), 42u32);
    assert_eq!(bounded_bump_u32(0), 1u32);
    assert_eq!(bounded_bump_u32(9), 10u32);
    assert_eq!(bounded_bump_u32(10), 10u32);
    assert_eq!(bounded_bump_u32(u32::MAX), 0u32);
    assert_eq!(option_default_u32(None, 8), 8u32);
    assert_eq!(option_default_u32(Some(3), 8), 3u32);
}

#[test]
fn surface_evaluator_matches_extracted_rust() {
    assert_eq!(add_u64(u64::MAX, 1), 0u64);
    assert_eq!(echo_char('z'), char::from_u32(122).unwrap());
    assert_eq!(echo_string(String::from("hi")), String::from("hi"));
    assert_eq!(echo_list_u32(vec![1, 2]), vec![1u32, 2u32]);
    assert_eq!(echo_array_u32(vec![3, 4]), vec![3u32, 4u32]);
    assert_eq!(list_map_inc_u32(vec![1, u32::MAX]), vec![2u32, 0u32]);
    assert_eq!(list_fold_sum_u32(vec![1, 2, u32::MAX]), 2u32);
    assert_eq!(
        list_map_add_capture_u32(5, vec![1, u32::MAX]),
        vec![6u32, 4u32]
    );
    assert_eq!(list_filter_nonzero_u32(vec![0, 1, 0, 2]), vec![1u32, 2u32]);
    assert_eq!(list_foldr_sum_u32(vec![1, 2, u32::MAX]), 2u32);
    assert_eq!(list_any_nonzero_u32(vec![0, 0, 7]), true);
    assert_eq!(list_any_nonzero_u32(vec![0, 0, 0]), false);
    assert_eq!(list_all_nonzero_u32(vec![1, 2, 3]), true);
    assert_eq!(list_all_nonzero_u32(vec![1, 0, 3]), false);
    assert_eq!(array_map_inc_u32(vec![1, u32::MAX]), vec![2u32, 0u32]);
    assert_eq!(array_fold_sum_u32(vec![1, 2, u32::MAX]), 2u32);
    assert_eq!(option_map_inc_u32(Some(41)), Some(42u32));
    assert_eq!(option_map_inc_u32(None), None::<u32>);
    assert_eq!(option_bind_inc_u32(Some(41)), Some(42u32));
    assert_eq!(option_bind_inc_u32(None), None::<u32>);
    assert_eq!(result_bind_inc_u32(Ok(u32::MAX)), Ok(0u32));
    assert_eq!(result_bind_inc_u32(Err(9)), Err(9u32));
    assert_eq!(nat_sum_to_u32(5), 10u32);
    assert_eq!(subtype_val_u32(42), 42u32);
    assert_eq!(subtype_inc_u32(41), 42u32);
    assert_eq!(subtype_roundtrip_u32(77), 77u32);
    assert_eq!(bounded_proof_make_u32(9), BoundedProof { value: 9u32 });
    assert_eq!(bounded_proof_value_u32(BoundedProof { value: 11 }), 11u32);
    assert_eq!(fin_val10_u32(7), 7u32);
    assert_eq!(fin_checked10_u32(9), Some(9u32));
    assert_eq!(fin_checked10_u32(10), None::<u32>);
    assert_eq!(fin_succ_checked10_u32(8), Some(9u32));
    assert_eq!(fin_succ_checked10_u32(9), None::<u32>);
    assert_eq!(vector_echo3_u32(vec![1, 2, 3]), vec![1u32, 2u32, 3u32]);
    assert_eq!(
        vector_map_inc3_u32(vec![1, 2, u32::MAX]),
        vec![2u32, 3u32, 0u32]
    );
    assert_eq!(general_bool_match_u32(true, 9, 20), 10u32);
    assert_eq!(general_bool_match_u32(false, 9, 20), 21u32);
    assert_eq!(general_option_match_u32(Some(41), 8), 42u32);
    assert_eq!(general_step_match_u32(Step::Jump(u32::MAX), 7), 0u32);
    assert_eq!(pair_sum_match_u32(40, 2), 42u32);
    assert_eq!(list_length_u32(vec![1, 2, 3]), 3u32);
    assert_eq!(tail_sum_down_u32(5), 15u32);
    assert_eq!(
        exact_nat_add(BigUint::from(40u32), BigUint::from(2u32)),
        BigUint::from(42u32)
    );
    assert_eq!(
        exact_nat_mul(BigUint::from(7u32), BigUint::from(6u32)),
        BigUint::from(42u32)
    );
    assert_eq!(
        exact_int_add(BigInt::from(-7i32), BigInt::from(5i32)),
        BigInt::from(-2i32)
    );
    assert_eq!(decidable_eq_u32(7, 7), true);
    assert_eq!(decidable_eq_u32(7, 8), false);
    assert_eq!(ord_compare_u32(1, 2), Ordering::Lt);
    assert_eq!(ord_compare_u32(2, 2), Ordering::Eq);
    assert_eq!(ord_compare_u32(3, 2), Ordering::Gt);
    assert_eq!(inhabited_default_u32(()), 0u32);
    assert_eq!(to_string_u32(42), String::from("42"));
    assert_eq!(repr_u32(42), String::from("42"));
    assert_eq!(option_do_inc_u32(Some(41)), Some(42u32));
    assert_eq!(option_do_inc_u32(None), None::<u32>);
    assert_eq!(closure_apply_capture_u32(5, 37), 42u32);
    assert_eq!(closure_env_apply_add_delta_u32(5, 37), 42u32);
    assert_eq!(
        closure_env_map_add_delta_u32(5, vec![1, u32::MAX]),
        vec![6u32, 4u32]
    );
    assert_eq!(defun_apply_u32(U32FnCase::Inc, 41), 42u32);
    assert_eq!(defun_apply_u32(U32FnCase::Double, 21), 42u32);
    assert_eq!(defun_apply_u32(U32FnCase::Add(5), 37), 42u32);
    assert_eq!(defun_compose_inc_double_u32(20), 42u32);
    assert_eq!(defun_apply_add5_u32(37), 42u32);
    assert_eq!(
        defun_map_selected_u32(false, vec![1, u32::MAX]),
        vec![2u32, 0u32]
    );
    assert_eq!(list_append_u32(vec![1, 2], vec![3]), vec![1u32, 2u32, 3u32]);
    assert_eq!(list_find_nonzero_u32(vec![0, 0, 7]), Some(7u32));
    assert_eq!(array_push_u32(vec![1, 2], 3), vec![1u32, 2u32, 3u32]);
    assert_eq!(option_getd_u32(None, 9), 9u32);
    assert_eq!(option_getd_u32(Some(4), 9), 4u32);
    assert_eq!(result_map_err_inc_u32(Err(41)), Err(42u32));
    assert_eq!(except_do_inc_u32(Ok(41)), Ok(42u32));
    assert_eq!(except_do_inc_u32(Err(7)), Err(7u32));
    assert_eq!(reader_add_env_u32(5, 37), 42u32);
    assert_eq!(state_tick_u32(41), (41u32, 42u32));
    assert_eq!(generic_beq_u32(7, 7), true);
    assert_eq!(generic_beq_u32(7, 8), false);
    assert_eq!(echo_prod_u32((5, 6)), (5u32, 6u32));
    assert_eq!(echo_sum_u32(Ok(7)), Ok(7u32));
    assert_eq!(echo_sum_u32(Err(8)), Err(8u32));
    assert_eq!(helper_chain_u32(40), 42u32);
    assert_eq!(proof_erased_u32(5), 5u32);
    assert_eq!(bool_match_u32(true, 1, 2), 1u32);
    assert_eq!(bool_match_u32(false, 1, 2), 2u32);
    assert_eq!(some_u32(4), Some(4u32));
    assert_eq!(none_u32(()), None::<u32>);
    assert_eq!(option_default_u32(None, 8), 8u32);
    assert_eq!(option_default_u32(Some(3), 8), 3u32);
    assert_eq!(result_ok_u32(5), Ok(5u32));
    assert_eq!(result_err_u32(7), Err(7u32));
    assert_eq!(choose_by_enum(Choice::First, 10, 20), 10u32);
    assert_eq!(choose_by_enum(Choice::Second, 10, 20), 20u32);
    assert_eq!(make_point(3, 4), Point { x: 3u32, y: 4u32 });
    assert_eq!(point_x(Point { x: 8, y: 9 }), 8u32);
    assert_eq!(point_y(Point { x: 8, y: 9 }), 9u32);
    assert_eq!(
        shift_point_x(Point { x: u32::MAX, y: 7 }, 1),
        Point { x: 0u32, y: 7u32 }
    );
    assert_eq!(boxed_u32(9), BoxedU32 { value: 9u32 });
    assert_eq!(boxed_value_u32(BoxedU32 { value: 9 }), 9u32);
    assert_eq!(tagged_missing_u32(()), TaggedU32::Missing);
    assert_eq!(tagged_present_u32(6), TaggedU32::Present(6u32));
    assert_eq!(tagged_default_u32(TaggedU32::Missing, 7), 7u32);
    assert_eq!(tagged_default_u32(TaggedU32::Present(6), 7), 6u32);
    assert_eq!(step_stay(()), Step::Stay);
    assert_eq!(step_jump(12), Step::Jump(12u32));
    assert_eq!(step_amount_or(Step::Stay, 9), 9u32);
    assert_eq!(step_amount_or(Step::Jump(12), 9), 12u32);
    assert_eq!(step_amount_plus_one_or(Step::Stay, 7), 7u32);
    assert_eq!(step_amount_plus_one_or(Step::Jump(u32::MAX), 7), 0u32);
    assert_eq!(inc_u32(41), 42u32);
    assert_eq!(inc_u32(u32::MAX), 0u32);
    assert_eq!(inc_twice_u32(40), 42u32);
    assert_eq!(inc_twice_u32(u32::MAX), 1u32);
    assert_eq!(nested_none_u32(()), Some(None::<u32>));
    assert_eq!(result_ok_none_u32(()), Ok(None::<u32>));
    assert_eq!(result_err_some_u32(44), Err(Some(44u32)));
    assert_eq!(identity_u64(99), 99u64);
    assert_eq!(choose_generic_u32(true, 10, 20), 10u32);
    assert_eq!(choose_generic_u32(false, 10, 20), 20u32);
    assert_eq!(option_default_u64(None, 77), 77u64);
    assert_eq!(option_default_u64(Some(55), 77), 55u64);
    assert_eq!(generic_identity__u32(11), 11u32);
    assert_eq!(auto_identity_u32(12), 12u32);
    assert_eq!(
        generic_choose__point(true, Point { x: 1, y: 2 }, Point { x: 3, y: 4 }),
        Point { x: 1u32, y: 2u32 }
    );
    assert_eq!(
        generic_choose__point(false, Point { x: 1, y: 2 }, Point { x: 3, y: 4 }),
        Point { x: 3u32, y: 4u32 }
    );
    assert_eq!(
        auto_choose_point(true, Point { x: 1, y: 2 }, Point { x: 3, y: 4 }),
        Point { x: 1u32, y: 2u32 }
    );
    assert_eq!(
        auto_choose_point(false, Point { x: 1, y: 2 }, Point { x: 3, y: 4 }),
        Point { x: 3u32, y: 4u32 }
    );
    assert_eq!(generic_option_default__step(None, Step::Stay), Step::Stay);
    assert_eq!(
        generic_option_default__step(Some(Step::Jump(7)), Step::Stay),
        Step::Jump(7u32)
    );
    assert_eq!(
        auto_option_default_step(None, Step::Jump(5)),
        Step::Jump(5u32)
    );
    assert_eq!(
        auto_option_default_step(Some(Step::Stay), Step::Jump(5)),
        Step::Stay
    );
}
