// Generated by LeanRustCore.Differential. Do not edit by hand.
// Expectations on the right-hand side are computed in Lean.

use lean_rust_core_generated::*;

#[test]
fn lean_evaluator_matches_generated_rust() {
    assert_eq!(clamp_u32(10, 20, 5), 10u32);
    assert_eq!(clamp_u32(10, 20, 25), 20u32);
    assert_eq!(clamp_u32(10, 20, 15), 15u32);
    assert_eq!(max_u32(3, 8), 8u32);
    assert_eq!(max_u32(8, 3), 8u32);
    assert!(!is_nonzero_u32(0));
    assert!(is_nonzero_u32(7));
    assert_eq!(add_u32(u32::MAX, 1), 0u32);
    assert_eq!(add_u32(40, 2), 42u32);
    assert_eq!(bounded_bump_u32(0), 1u32);
    assert_eq!(bounded_bump_u32(9), 10u32);
    assert_eq!(bounded_bump_u32(10), 10u32);
    assert_eq!(bounded_bump_u32(u32::MAX), 0u32);
    assert_eq!(option_default_u32(None, 8), 8u32);
    assert_eq!(option_default_u32(Some(3), 8), 3u32);
}

#[test]
fn extracted_declarations_keep_expected_surface_semantics() {
    assert_eq!(add_u64(u64::MAX, 1), 0u64);
    assert_eq!(bool_match_u32(true, 1, 2), 1u32);
    assert_eq!(bool_match_u32(false, 1, 2), 2u32);
    assert_eq!(some_u32(4), Some(4u32));
    assert_eq!(none_u32(()), None::<u32>);
    assert_eq!(step_amount_or(Step::Stay, 9), 9u32);
    assert_eq!(step_amount_or(Step::Jump(12), 9), 12u32);
    assert_eq!(inc_twice_u32(40), 42u32);
    assert_eq!(inc_twice_u32(u32::MAX), 1u32);
    assert_eq!(choose_generic_u32(true, 10, 20), 10u32);
    assert_eq!(choose_generic_u32(false, 10, 20), 20u32);
    assert_eq!(option_default_u64(None, 77), 77u64);
    assert_eq!(option_default_u64(Some(55), 77), 55u64);
}
