import LeanRustCore.Examples
import LeanRustCore.ChimeraBoundary

namespace LeanRustCore.BoundaryExport

open LeanRustCore
open LeanRustCore.Examples

/-!
Phase-4 raw ABI boundary exporter.

This module deliberately does **not** change the direct safe Rust lane.  It emits
an optional, feature-gated Rust wrapper module for a conservative C-compatible
subset of the already generated Rust functions.  Primitive values cross directly;
`Bool` crosses as `u32`; `Result<u32,u32>` crosses as `ChStatus` plus `out_ok` and
`out_err` pointers.  Rich Rust-native values such as `String`, `Vec`, structs,
enums, and `Option` remain outside the raw ABI lane.
-/

private def abiScalarType : RType → Option String
  | .bool => some "u32"
  | .u32 => some "u32"
  | .u64 => some "u64"
  | .i32 => some "i32"
  | .i64 => some "i64"
  | _ => none

private def abiArgDecl (arg : RArg) : Option String := do
  let ty ← abiScalarType arg.2
  pure (rustValueIdent "arg" arg.1 ++ ": " ++ ty)

private def rustCallArg (arg : RArg) : String :=
  let name := rustValueIdent "arg" arg.1
  match arg.2 with
  | .bool => name ++ " != 0"
  | _ => name

private def rustDirectReturn (ret : RType) (call : String) : String :=
  match ret with
  | .bool => "if " ++ call ++ " { 1 } else { 0 }"
  | _ => call

private def wrapperName (name : String) : String :=
  rustValueIdent "ffi_export" ("lrc_" ++ name)

private def directWrapper? (f : SurfaceFun) : Option String := do
  let retTy ← abiScalarType f.ret
  let argDecls ← f.args.mapM abiArgDecl
  let rustName := rustValueIdent "generated" f.name
  let call := "crate::" ++ rustName ++ "(" ++ joinWith ", " (f.args.map rustCallArg) ++ ")"
  pure <|
    "#[no_mangle]\n" ++
    "pub extern \"C\" fn " ++ wrapperName f.name ++ "(" ++ joinWith ", " argDecls ++ ") -> " ++ retTy ++ " {\n" ++
    "    " ++ rustDirectReturn f.ret call ++ "\n" ++
    "}\n"

private def resultU32U32Wrapper? (f : SurfaceFun) : Option String := do
  match f.ret with
  | .result .u32 .u32 =>
      let argDecls ← f.args.mapM abiArgDecl
      let rustName := rustValueIdent "generated" f.name
      let fullArgs := argDecls ++ ["out_ok: *mut u32", "out_err: *mut u32"]
      let call := "crate::" ++ rustName ++ "(" ++ joinWith ", " (f.args.map rustCallArg) ++ ")"
      pure <|
        "#[no_mangle]\n" ++
        "pub unsafe extern \"C\" fn " ++ wrapperName f.name ++ "(" ++ joinWith ", " fullArgs ++ ") -> ChStatus {\n" ++
        "    unsafe { crate::abi::lower_result_u32_u32(" ++ call ++ ", out_ok, out_err) }\n" ++
        "}\n"
  | _ => none

private def boundaryWrapper? (f : SurfaceFun) : Option String :=
  match resultU32U32Wrapper? f with
  | some wrapper => some wrapper
  | none => directWrapper? f

/-- Wrappers generated for the current conservative raw ABI subset. -/
def boundaryWrappers : List String :=
  LeanRustCore.Examples.extractedSurfaceFunctions.filterMap boundaryWrapper?

/-- Number of generated raw ABI wrappers. -/
def boundaryExportCount : Nat :=
  boundaryWrappers.length

/-- Optional Rust raw-ABI wrapper module. It is included only under the Rust `ffi` feature. -/
def generatedBoundaryRust : String :=
  "// Generated by LeanRustCore.BoundaryExport. Do not edit by hand.\n" ++
  "// This module is feature-gated by rust/src/lib.rs and is not part of the default safe direct-emission lane.\n\n" ++
  "#![allow(clippy::missing_safety_doc)]\n\n" ++
  "use crate::abi::ChStatus;\n\n" ++
  joinWith "\n" boundaryWrappers

end LeanRustCore.BoundaryExport
