import LeanRustCore.Examples

namespace LeanRustCore.Differential

open LeanRustCore
open LeanRustCore.Examples

/-!
Step 7 differential fixtures.

The values below are computed in Lean from the proof-carrying IR evaluator and
then rendered as Rust assertions against the generated Rust functions. That makes
`rust/tests/differential_generated.rs` a cross-language differential test: the
right hand side is Lean's evaluator result, while the left hand side calls the
Rust emitted by the extractor.
-/

structure RustAssertion where
  expression : String
  expected : String
  deriving Repr, BEq

private def rustU32 (n : Nat) : String :=
  Nat.toString (u32Wrap n) ++ "u32"

private def rustU64 (n : Nat) : String :=
  Nat.toString (u64Wrap n) ++ "u64"

private def rustBool (b : Bool) : String :=
  if b then "true" else "false"

private def rustOptionU32 : Option Nat → String
  | none => "None::<u32>"
  | some value => "Some(" ++ rustU32 value ++ ")"

private def clampExpected (lo hi x : Nat) : String :=
  rustU32 (eval clampBody { lo := lo, hi := hi, x := x })

private def maxExpected (a b : Nat) : String :=
  rustU32 (eval maxBody { a := a, b := b })

private def nonzeroExpected (x : Nat) : String :=
  rustBool (eval nonzeroBody { x := x })

private def addExpected (a b : Nat) : String :=
  rustU32 (eval addBody { a := a, b := b })

private def bumpExpected (x : Nat) : String :=
  rustU32 (eval boundedBumpBody { x := x })

private def optionDefaultExpected (x : Option Nat) (fallback : Nat) : String :=
  rustU32 (eval optionDefaultBody { x := x, fallback := fallback })

private def assertion (expression expected : String) : RustAssertion :=
  { expression := expression, expected := expected }

/-- Differential assertions whose expectations are rendered from Lean evaluator results. -/
def evaluatorAssertions : List RustAssertion := [
  assertion "clamp_u32(10, 20, 5)" (clampExpected 10 20 5),
  assertion "clamp_u32(10, 20, 25)" (clampExpected 10 20 25),
  assertion "clamp_u32(10, 20, 15)" (clampExpected 10 20 15),
  assertion "max_u32(3, 8)" (maxExpected 3 8),
  assertion "max_u32(8, 3)" (maxExpected 8 3),
  assertion "is_nonzero_u32(0)" (nonzeroExpected 0),
  assertion "is_nonzero_u32(7)" (nonzeroExpected 7),
  assertion "add_u32(u32::MAX, 1)" (addExpected (u32Modulus - 1) 1),
  assertion "add_u32(40, 2)" (addExpected 40 2),
  assertion "bounded_bump_u32(0)" (bumpExpected 0),
  assertion "bounded_bump_u32(9)" (bumpExpected 9),
  assertion "bounded_bump_u32(10)" (bumpExpected 10),
  assertion "bounded_bump_u32(u32::MAX)" (bumpExpected (u32Modulus - 1)),
  assertion "option_default_u32(None, 8)" (optionDefaultExpected none 8),
  assertion "option_default_u32(Some(3), 8)" (optionDefaultExpected (some 3) 8)
]

/-- Additional extracted-declaration cases that complement the evaluator-backed assertions. -/
def extractedDeclarationAssertions : List RustAssertion := [
  assertion "add_u64(u64::MAX, 1)" (rustU64 (u64Modulus - 1 + 1)),
  assertion "bool_match_u32(true, 1, 2)" (rustU32 1),
  assertion "bool_match_u32(false, 1, 2)" (rustU32 2),
  assertion "some_u32(4)" (rustOptionU32 (some 4)),
  assertion "none_u32(())" (rustOptionU32 none),
  assertion "choose_generic_u32(true, 10, 20)" (rustU32 10),
  assertion "choose_generic_u32(false, 10, 20)" (rustU32 20),
  assertion "option_default_u64(None, 77)" (rustU64 77),
  assertion "option_default_u64(Some(55), 77)" (rustU64 55)
]

private def emitAssertion (a : RustAssertion) : String :=
  if a.expected == "true" then
    "    assert!(" ++ a.expression ++ ");"
  else if a.expected == "false" then
    "    assert!(!" ++ a.expression ++ ");"
  else
    "    assert_eq!(" ++ a.expression ++ ", " ++ a.expected ++ ");"

private def emitAssertionsTest (name : String) (assertions : List RustAssertion) : String :=
  "#[test]\nfn " ++ name ++ "() {\n" ++
  joinWith "\n" (assertions.map emitAssertion) ++
  "\n}\n"

/-- Rust integration-test source generated from the Lean differential fixtures. -/
def generatedDifferentialRustTests : String :=
  "// Generated by LeanRustCore.Differential. Do not edit by hand.\n" ++
  "// Expectations on the right-hand side are computed in Lean.\n\n" ++
  "use lean_rust_core_generated::*;\n\n" ++
  emitAssertionsTest "lean_evaluator_matches_generated_rust" evaluatorAssertions ++
  "\n" ++
  emitAssertionsTest "extracted_declarations_keep_expected_surface_semantics" extractedDeclarationAssertions

end LeanRustCore.Differential
