import LeanRustCore.IR
import LeanRustCore.Surface

namespace LeanRustCore

/-- Small dependency-free string join. -/
def joinWith (sep : String) : List String → String
  | [] => ""
  | [x] => x
  | x :: xs => x ++ sep ++ joinWith sep xs

/-- Rust spelling for the current IR type subset. -/
def rustType : RType → String
  | .unit => "()"
  | .bool => "bool"
  | .u32 => "u32"
  | .u64 => "u64"
  | .option t => "Option<" ++ rustType t ++ ">"
  | .result ok err => "Result<" ++ rustType ok ++ ", " ++ rustType err ++ ">"

/-- Emit a valid Rust expression for the proof-carrying typed subset. -/
def emitExpr {ctx : Type} : {t : RType} → RExpr ctx t → String
  | _, .var name _ => name
  | _, .litUnit => "()"
  | _, .litBool true => "true"
  | _, .litBool false => "false"
  | _, .litU32 n => Nat.toString n
  | _, .litU64 n => Nat.toString n
  | _, .letIn name value body => "{ let " ++ name ++ " = " ++ emitExpr value ++ "; " ++ emitExpr body ++ " }"
  | _, .ite c a b => "if " ++ emitExpr c ++ " { " ++ emitExpr a ++ " } else { " ++ emitExpr b ++ " }"
  | _, .not a => "(!" ++ emitExpr a ++ ")"
  | _, .and a b => "(" ++ emitExpr a ++ " && " ++ emitExpr b ++ ")"
  | _, .or a b => "(" ++ emitExpr a ++ " || " ++ emitExpr b ++ ")"
  | _, .eqU32 a b => "(" ++ emitExpr a ++ " == " ++ emitExpr b ++ ")"
  | _, .ltU32 a b => "(" ++ emitExpr a ++ " < " ++ emitExpr b ++ ")"
  | _, .leU32 a b => "(" ++ emitExpr a ++ " <= " ++ emitExpr b ++ ")"
  | _, .gtU32 a b => "(" ++ emitExpr a ++ " > " ++ emitExpr b ++ ")"
  | _, .geU32 a b => "(" ++ emitExpr a ++ " >= " ++ emitExpr b ++ ")"
  | _, .addU32 a b => "(" ++ emitExpr a ++ ").wrapping_add(" ++ emitExpr b ++ ")"
  | _, .subU32 a b => "(" ++ emitExpr a ++ ").wrapping_sub(" ++ emitExpr b ++ ")"
  | _, .mulU32 a b => "(" ++ emitExpr a ++ ").wrapping_mul(" ++ emitExpr b ++ ")"
  | _, .minU32 a b => "core::cmp::min(" ++ emitExpr a ++ ", " ++ emitExpr b ++ ")"
  | _, .maxU32 a b => "core::cmp::max(" ++ emitExpr a ++ ", " ++ emitExpr b ++ ")"
  | _, .optionNone => "None"
  | _, .optionSome a => "Some(" ++ emitExpr a ++ ")"
  | _, .resultOk a => "Ok(" ++ emitExpr a ++ ")"
  | _, .resultErr e => "Err(" ++ emitExpr e ++ ")"

/-- Emit the extracted first-order surface subset. -/
partial def emitSurfaceExpr : SurfaceExpr → String
  | .var name => name
  | .litUnit => "()"
  | .litBool true => "true"
  | .litBool false => "false"
  | .litU32 n => Nat.toString n
  | .litU64 n => Nat.toString n
  | .letIn name value body => "{ let " ++ name ++ " = " ++ emitSurfaceExpr value ++ "; " ++ emitSurfaceExpr body ++ " }"
  | .ite c a b => "if " ++ emitSurfaceExpr c ++ " { " ++ emitSurfaceExpr a ++ " } else { " ++ emitSurfaceExpr b ++ " }"
  | .not a => "(!" ++ emitSurfaceExpr a ++ ")"
  | .and a b => "(" ++ emitSurfaceExpr a ++ " && " ++ emitSurfaceExpr b ++ ")"
  | .or a b => "(" ++ emitSurfaceExpr a ++ " || " ++ emitSurfaceExpr b ++ ")"
  | .eqU32 a b => "(" ++ emitSurfaceExpr a ++ " == " ++ emitSurfaceExpr b ++ ")"
  | .ltU32 a b => "(" ++ emitSurfaceExpr a ++ " < " ++ emitSurfaceExpr b ++ ")"
  | .leU32 a b => "(" ++ emitSurfaceExpr a ++ " <= " ++ emitSurfaceExpr b ++ ")"
  | .gtU32 a b => "(" ++ emitSurfaceExpr a ++ " > " ++ emitSurfaceExpr b ++ ")"
  | .geU32 a b => "(" ++ emitSurfaceExpr a ++ " >= " ++ emitSurfaceExpr b ++ ")"
  | .addU32 a b => "(" ++ emitSurfaceExpr a ++ ").wrapping_add(" ++ emitSurfaceExpr b ++ ")"
  | .subU32 a b => "(" ++ emitSurfaceExpr a ++ ").wrapping_sub(" ++ emitSurfaceExpr b ++ ")"
  | .mulU32 a b => "(" ++ emitSurfaceExpr a ++ ").wrapping_mul(" ++ emitSurfaceExpr b ++ ")"
  | .minU32 a b => "core::cmp::min(" ++ emitSurfaceExpr a ++ ", " ++ emitSurfaceExpr b ++ ")"
  | .maxU32 a b => "core::cmp::max(" ++ emitSurfaceExpr a ++ ", " ++ emitSurfaceExpr b ++ ")"
  | .optionNone _ => "None"
  | .optionSome a => "Some(" ++ emitSurfaceExpr a ++ ")"
  | .resultOk a => "Ok(" ++ emitSurfaceExpr a ++ ")"
  | .resultErr e => "Err(" ++ emitSurfaceExpr e ++ ")"

/-- Emit one Rust function argument. -/
def emitArg (arg : RArg) : String :=
  arg.1 ++ ": " ++ rustType arg.2

/-- Emit a safe Rust function from proof-carrying typed IR. -/
def emitFun (f : RFun) : String :=
  "pub fn " ++ f.name ++ "(" ++ joinWith ", " (f.args.map emitArg) ++ ") -> " ++
    rustType f.ret ++ " {\n    " ++ emitExpr f.body ++ "\n}\n"

/-- Emit a safe Rust function from extracted surface IR. -/
def emitSurfaceFun (f : SurfaceFun) : String :=
  "pub fn " ++ f.name ++ "(" ++ joinWith ", " (f.args.map emitArg) ++ ") -> " ++
    rustType f.ret ++ " {\n    " ++ emitSurfaceExpr f.body ++ "\n}\n"

/-- Emit a whole generated module from proof-carrying functions. -/
def emitRustModule (fns : List RFun) : String :=
  "// Generated by LeanRustCore. Do not edit by hand.\n" ++
  "// The checked-in rust/src/generated.rs is a fallback snapshot; scripts/gen.sh regenerates it.\n\n" ++
  joinWith "\n" (fns.map emitFun)

/-- Emit a whole generated module from extracted Lean declarations. -/
def emitSurfaceRustModule (fns : List SurfaceFun) : String :=
  "// Generated by LeanRustCore from elaborated Lean declarations. Do not edit by hand.\n" ++
  "// The checked-in rust/src/generated.rs is a fallback snapshot; scripts/gen.sh regenerates it.\n\n" ++
  joinWith "\n" (fns.map emitSurfaceFun)

end LeanRustCore
